server:
  port: 8000
  
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic

process-parallel:
  number-threads: 2

comission: 0.7 


