server:
  port: 8000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000

feign:
  hystrix:
    enabled: true
  client:
    hotelBroker:
      url: 'https://cvcbackendhotel.herokuapp.com/hotels/'
    config:
      default:
        loggerLevel: basic
     

process-parallel:
  number-threads: 2

comission: 0.7




